"""RustFS-backed object storage for item images."""

from app.db.storage.objects import _download_object
from app.db.storage.objects import _stream_object
from app.db.storage.paths import PROXY_IMAGE_CACHE_CONTROL
from app.db.storage.paths import _delete_object_if_present
from app.db.storage.paths import _get_object_key
from app.db.storage.paths import _get_storage_client
from app.db.storage.paths import _guess_content_type
from app.db.storage.paths import _prepare_square_image_variants
from app.db.storage.paths import _raise_rustfs_head_bucket_error
from app.db.storage.paths import _resolve_rustfs_s3_host_header
from app.db.storage.paths import _rustfs_endpoint_host_header
from app.db.storage.paths import _upload_bytes
from app.db.storage.paths import settings
from app.db.storage.objects import ImageVariant
from app.db.storage.objects import StoredImageObjectNotFoundError
from app.db.storage.objects import StoredImagePayload
from app.db.storage.objects import StoredImageStreamPayload
from app.db.storage.objects import backfill_item_image_thumbnails
from app.db.storage.objects import build_expense_item_image_path
from app.db.storage.objects import build_expense_item_image_thumb_path
from app.db.storage.objects import build_inventory_item_image_path
from app.db.storage.objects import build_inventory_item_image_thumb_path
from app.db.storage.objects import build_item_image_path
from app.db.storage.objects import build_item_image_thumb_path
from app.db.storage.objects import close_stored_image_stream
from app.db.storage.objects import delete_expense_item_image
from app.db.storage.objects import delete_inventory_item_image
from app.db.storage.objects import delete_item_image
from app.db.storage.objects import delete_item_image_storage
from app.db.storage.objects import ensure_bucket_exists
from app.db.storage.objects import format_image_last_modified
from app.db.storage.objects import get_expense_item_image_response_payload
from app.db.storage.objects import get_inventory_item_image_response_payload
from app.db.storage.objects import get_item_image_response_payload
from app.db.storage.objects import image_response_headers
from app.db.storage.objects import iter_stored_image_stream
from app.db.storage.objects import migrate_item_image_data_to_rustfs
from app.db.storage.objects import save_expense_item_image_content
from app.db.storage.objects import save_expense_item_image_upload
from app.db.storage.objects import save_inventory_item_image_content
from app.db.storage.objects import save_inventory_item_image_upload
from app.db.storage.objects import save_item_image_content
from app.db.storage.objects import save_item_image_upload
from app.db.storage.objects import upload_item_image
