"""add_purchase_rate_history

Revision ID: 0f40690b114f
Revises: 7cfc6be14d65
Create Date: 2026-06-27 12:21:34.276347
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '0f40690b114f'
down_revision: Union[str, None] = '7cfc6be14d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_item_purchase_rate_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_inventory_item_purchase_rate_history_inventory_item_id_inventory_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_item_purchase_rate_history')),
    sa.UniqueConstraint('inventory_item_id', 'date', name='uq_inventory_item_purchase_rate_history_item_date')
    )
    op.create_index('ix_inventory_item_purchase_rate_history_date', 'inventory_item_purchase_rate_history', ['date'], unique=False)
    op.create_index(op.f('ix_inventory_item_purchase_rate_history_id'), 'inventory_item_purchase_rate_history', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_item_purchase_rate_history_inventory_item_id'), 'inventory_item_purchase_rate_history', ['inventory_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_item_purchase_rate_history_inventory_item_id'), table_name='inventory_item_purchase_rate_history')
    op.drop_index(op.f('ix_inventory_item_purchase_rate_history_id'), table_name='inventory_item_purchase_rate_history')
    op.drop_index('ix_inventory_item_purchase_rate_history_date', table_name='inventory_item_purchase_rate_history')
    op.drop_table('inventory_item_purchase_rate_history')
    # ### end Alembic commands ###
