"""Add transfer shops and audit logs

Revision ID: 7cfc6be14d65
Revises: fb0d2b791bbc
Create Date: 2026-06-23 12:15:54.691152
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "7cfc6be14d65"
down_revision: Union[str, None] = "fb0d2b791bbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.dialects import postgresql

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transfer_shops",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tamil_name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(name)) >= 2",
            name=op.f("ck_transfer_shops_ck_transfer_shops_name_not_blank"),
        ),
        sa.CheckConstraint(
            "length(trim(tamil_name)) >= 1",
            name=op.f("ck_transfer_shops_ck_transfer_shops_tamil_name_not_blank"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transfer_shops")),
    )
    op.create_index(
        op.f("ix_transfer_shops_created_at"), "transfer_shops", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_transfer_shops_id"), "transfer_shops", ["id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("shop_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_audit_logs_shop_id_shops"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(op.f("ix_audit_logs_shop_id"), "audit_logs", ["shop_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "inventory_transfers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_shop_id", sa.Uuid(), nullable=False),
        sa.Column("transfer_shop_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column(
            "unit",
            postgresql.ENUM("KG", "UNIT", name="baseunit", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=op.f("ck_inventory_transfers_ck_inventory_transfers_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["inventory_item_id"],
            ["inventory_items.id"],
            name=op.f("fk_inventory_transfers_inventory_item_id_inventory_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_shop_id"],
            ["shops.id"],
            name=op.f("fk_inventory_transfers_source_shop_id_shops"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_shop_id"],
            ["transfer_shops.id"],
            name=op.f("fk_inventory_transfers_transfer_shop_id_transfer_shops"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_transfers")),
    )
    op.create_index(
        op.f("ix_inventory_transfers_created_at"),
        "inventory_transfers",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_inventory_transfers_id"), "inventory_transfers", ["id"], unique=False)
    op.create_index(
        op.f("ix_inventory_transfers_inventory_item_id"),
        "inventory_transfers",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_transfers_shop_item_created",
        "inventory_transfers",
        ["source_shop_id", "inventory_item_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transfers_source_shop_id"),
        "inventory_transfers",
        ["source_shop_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_transfers_transfer_shop_created",
        "inventory_transfers",
        ["transfer_shop_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transfers_transfer_shop_id"),
        "inventory_transfers",
        ["transfer_shop_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_transfers_transfer_shop_id"), table_name="inventory_transfers")
    op.drop_index("ix_inventory_transfers_transfer_shop_created", table_name="inventory_transfers")
    op.drop_index(op.f("ix_inventory_transfers_source_shop_id"), table_name="inventory_transfers")
    op.drop_index("ix_inventory_transfers_shop_item_created", table_name="inventory_transfers")
    op.drop_index(
        op.f("ix_inventory_transfers_inventory_item_id"), table_name="inventory_transfers"
    )
    op.drop_index(op.f("ix_inventory_transfers_id"), table_name="inventory_transfers")
    op.drop_index(op.f("ix_inventory_transfers_created_at"), table_name="inventory_transfers")
    op.drop_table("inventory_transfers")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_shop_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_transfer_shops_id"), table_name="transfer_shops")
    op.drop_index(op.f("ix_transfer_shops_created_at"), table_name="transfer_shops")
    op.drop_table("transfer_shops")
    # ### end Alembic commands ###
