"""drop inventory movement quantity positive constraint

Revision ID: d199bf838d3f
Revises: 0f40690b114f
Create Date: 2026-06-27 13:18:12.715627
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd199bf838d3f'
down_revision: Union[str, None] = '0f40690b114f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'tamil_name')
    # ### end Alembic commands ###
    op.drop_constraint('ck_inventory_movements_quantity_positive', 'inventory_movements', type_='check')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('tamil_name', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint('ck_inventory_movements_quantity_positive', 'inventory_movements', 'quantity > 0')
